language: erlang
services:
  - mongodb
notifications:
  recipients:
    - jerp@checkiz.com
otp_release:
  - 17.4
before_script:
  - sleep 15
  - mix deps.get --only test
script: "MIX_ENV=test mix do deps.get, test"
